const flights = [
  {
    id: "1",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "10.00",
    uçuşSüresi: "1 saat",
    varışSaati: "11.00",
    fiyat: "1200₺",
  },
  {
    id: "2",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "1200₺",
  },
  {
    id: "3",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "14.00",
    uçuşSüresi: "1 saat",
    varışSaati: "15.00",
    fiyat: "1200₺",
  },
  {
    id: "4",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "16.00",
    uçuşSüresi: "1 saat",
    varışSaati: "17.00",
    fiyat: "1200₺",
  },
  {
    id: "5",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "6",
    nereden: "İstanbul",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "10.00",
    uçuşSüresi: "1 saat",
    varışSaati: "11.00",
    fiyat: "1200₺",
  },
  {
    id: "7",
    nereden: "İstanbul",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "1200₺",
  },
  {
    id: "8",
    nereden: "İstanbul",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "14.00",
    uçuşSüresi: "1 saat",
    varışSaati: "15.00",
    fiyat: "1200₺",
  },
  {
    id: "9",
    nereden: "İstanbul",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "16.00",
    uçuşSüresi: "1 saat",
    varışSaati: "17.00",
    fiyat: "1200₺",
  },
  {
    id: "10",
    nereden: "İstanbul",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "11",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "12",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "10.00",
    uçuşSüresi: "1 saat",
    varışSaati: "11.00",
    fiyat: "1200₺",
  },
  {
    id: "13",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "1200₺",
  },
  {
    id: "14",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "14.00",
    uçuşSüresi: "1 saat",
    varışSaati: "15.00",
    fiyat: "1200₺",
  },
  {
    id: "15",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "16.00",
    uçuşSüresi: "1 saat",
    varışSaati: "17.00",
    fiyat: "1200₺",
  },
  {
    id: "16",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "17",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "10.00",
    uçuşSüresi: "1 saat",
    varışSaati: "11.00",
    fiyat: "1200₺",
  },
  {
    id: "18",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "1200₺",
  },
  {
    id: "19",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "14.00",
    uçuşSüresi: "1 saat",
    varışSaati: "15.00",
    fiyat: "1200₺",
  },
  {
    id: "20",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "16.00",
    uçuşSüresi: "1 saat",
    varışSaati: "17.00",
    fiyat: "1200₺",
  },
  {
    id: "21",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "22",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "10.00",
    uçuşSüresi: "1 saat",
    varışSaati: "11.00",
    fiyat: "1200₺",
  },
  {
    id: "23",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-28").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "1200₺",
  },
  {
    id: "24",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-28").toLocaleDateString(),
    kalkışSaati: "14.00",
    uçuşSüresi: "1 saat",
    varışSaati: "15.00",
    fiyat: "1200₺",
  },
  {
    id: "25",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-29").toLocaleDateString(),
    kalkışSaati: "16.00",
    uçuşSüresi: "1 saat",
    varışSaati: "17.00",
    fiyat: "1200₺",
  },
  {
    id: "26",
    nereden: "Ankara",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-30").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "27",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "28",
    nereden: "Adana",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "900₺",
  },
  {
    id: "29",
    nereden: "Adana",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "900₺",
  },
  {
    id: "30",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "31",
    nereden: "Adana",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "900₺",
  },
  {
    id: "32",
    nereden: "Adana",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "900₺",
  },
  {
    id: "33",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-28").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "34",
    nereden: "Adana",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-29").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "900₺",
  },
  {
    id: "35",
    nereden: "Adana",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-30").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "900₺",
  },
  {
    id: "36",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-30").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "37",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-29").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "38",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "39",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "40",
    nereden: "Antalya",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  ,
  {
    id: "41",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "12.00",
    uçuşSüresi: "1 saat",
    varışSaati: "13.00",
    fiyat: "1200₺",
  },
  {
    id: "42",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "43",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "44",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "45",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "46",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-28").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "47",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-29").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "48",
    nereden: "Ankara",
    nereye: "Antalya",
    gidişTarihi: new Date("2023-08-30").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "49",
    nereden: "Ankara",
    nereye: "Bursa",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "50",
    nereden: "Ankara",
    nereye: "Bursa",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "51",
    nereden: "Ankara",
    nereye: "Bursa",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "52",
    nereden: "Ankara",
    nereye: "Bursa",
    gidişTarihi: new Date("2023-08-26").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "53",
    nereden: "Ankara",
    nereye: "Bursa",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "54",
    nereden: "Ankara",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "55",
    nereden: "İzmir",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "56",
    nereden: "Ankara",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "57",
    nereden: "İzmir",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-24").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "57",
    nereden: "Ankara",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "58",
    nereden: "İzmir",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "59",
    nereden: "Ankara",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "60",
    nereden: "İzmir",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-27").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "61",
    nereden: "Ankara",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-29").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "62",
    nereden: "İzmir",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-29").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "63",
    nereden: "Ankara",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-30").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "64",
    nereden: "İzmir",
    nereye: "Ankara",
    gidişTarihi: new Date("2023-08-30").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "65",
    nereden: "İstanbul",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "66",
    nereden: "İzmir",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-23").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "67",
    nereden: "İstanbul",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "68",
    nereden: "İzmir",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-25").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "69",
    nereden: "İstanbul",
    nereye: "İzmir",
    gidişTarihi: new Date("2023-08-28").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
  {
    id: "70",
    nereden: "İzmir",
    nereye: "İstanbul",
    gidişTarihi: new Date("2023-08-28").toLocaleDateString(),
    kalkışSaati: "18.00",
    uçuşSüresi: "1 saat",
    varışSaati: "19.00",
    fiyat: "1200₺",
  },
];

module.exports = {
  flights: flights,
};
